apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"angular","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"angular"}},"template":{"metadata":{"labels":{"app":"angular"}},"spec":{"containers":[{"image":"ghaythsel404/angular:v3","name":"angular","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2024-05-12T15:37:27Z"
  generation: 4
  name: angular
  namespace: default
  resourceVersion: "262075"
  uid: 0d65c6ce-6f7c-44e0-8d38-4adbb6e2565c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: angular
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: angular
    spec:
      containers:
      - image: rbaihis/deploy:angular_v2
        imagePullPolicy: IfNotPresent
        name: angular
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-12T15:37:27Z"
    lastUpdateTime: "2024-06-11T22:26:31Z"
    message: ReplicaSet "angular-8d5b666b8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-06-12T03:58:02Z"
    lastUpdateTime: "2024-06-12T03:58:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
