apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"grafana"},"name":"grafana","namespace":"default"},"spec":{"ports":[{"name":"grafana","nodePort":30300,"port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"grafana"},"type":"NodePort"}}
  creationTimestamp: "2024-03-06T08:20:03Z"
  labels:
    app: grafana
  name: grafana
  namespace: default
  resourceVersion: "103242"
  uid: 976e559d-efc6-4c76-9fea-9627860237a8
spec:
  clusterIP: 10.254.8.9
  clusterIPs:
  - 10.254.8.9
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grafana
    nodePort: 30300
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
