apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-03-02T23:30:45Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "210"
  uid: f66e1723-6a5d-4720-be45-fa2e1a903c95
spec:
  clusterIP: 10.254.0.1
  clusterIPs:
  - 10.254.0.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
