apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"prometheus"},"name":"prometheus","namespace":"default"},"spec":{"ports":[{"name":"prometheus","nodePort":30990,"port":9090,"protocol":"TCP","targetPort":9090}],"selector":{"app":"prometheus"},"type":"NodePort"}}
  creationTimestamp: "2024-03-04T18:08:13Z"
  labels:
    app: prometheus
  name: prometheus
  namespace: default
  resourceVersion: "90100"
  uid: 95e2865b-3390-456f-9e14-5deb34a28069
spec:
  clusterIP: 10.254.207.71
  clusterIPs:
  - 10.254.207.71
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: prometheus
    nodePort: 30990
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
